name: CI - Foundry (fmt, build, tests, gas)

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  foundry:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Foundry (foundryup)
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          # add foundry to PATH for this session
          echo "$HOME/.foundry/bin" >> $GITHUB_PATH
          # show versions
          foundryup --version || true
          forge --version || true
          cast --version || true
          anvil --version || true

      - name: Install dependencies
        run: forge install --no-commit

      - name: Check formatting (forge fmt)
        run: forge fmt --check

      - name: Build
        run: forge build

      - name: Run tests (with gas report)
        run: |
          forge test -vv --gas-report | tee gas-report.txt

      - name: Upload gas report
        uses: actions/upload-artifact@v4
        with:
          name: gas-report
          path: gas-report.txt
