name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          source ~/.bashrc || true
          foundryup || true
      - name: Install deps
        run: |
          forge install || true
      - name: Run tests
        run: |
          forge test -vv
